services:
  gateway:
    build:
      context: .
      dockerfile: gateway/BG.Gateway/Dockerfile
    container_name: bg-gateway
    ports:
      - "8080:8080"
    depends_on:
      - identity-service
      - userprofile-service
      - post-service
      - feed-service
      - socialgraph-service
      - interaction-service
      - notification-service
      - search-service
      - topic-service
      - media-service
  identity-service:
    build:
      context: .
      dockerfile: services/BG.IdentityService/Dockerfile
    container_name: bg-identity-service
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8081
  userprofile-service:
    build:
      context: .
      dockerfile: services/BG.UserProfileService/Dockerfile
    container_name: bg-userprofile-service
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8082
  post-service:
    build:
      context: .
      dockerfile: services/BG.PostService/Dockerfile
    container_name: bg-post-service
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8083
  feed-service:
    build:
      context: .
      dockerfile: services/BG.FeedService/Dockerfile
    container_name: bg-feed-service
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8084
  socialgraph-service:
    build:
      context: .
      dockerfile: services/BG.SocialGraphService/Dockerfile
    container_name: bg-socialgraph-service
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8085
  interaction-service:
    build:
      context: .
      dockerfile: services/BG.InteractionService/Dockerfile
    container_name: bg-interaction-service
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8086
  notification-service:
    build:
      context: .
      dockerfile: services/BG.NotificationService/Dockerfile
    container_name: bg-notification-service
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8087
  search-service:
    build:
      context: .
      dockerfile: services/BG.SearchService/Dockerfile
    container_name: bg-search-service
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8088
  topic-service:
    build:
      context: .
      dockerfile: services/BG.TopicService/Dockerfile
    container_name: bg-topic-service
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8089
  media-service:
    build:
      context: .
      dockerfile: services/BG.MediaService/Dockerfile
    container_name: bg-media-service
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:8090
