<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="BG.SharedKernel\Commands\" />
    <Folder Include="BG.SharedKernel\DTOs\" />
    <Folder Include="BG.SharedKernel\Exceptions\" />
  </ItemGroup>

</Project>
